# Generated by Django 4.0.5 on 2022-07-03 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('moderations', '0002_alter_report_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='moderations.state'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('target_content_type', 'target_object_id')},
        ),
    ]
