# Generated by Django 4.0.5 on 2022-07-03 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderations', '0003_alter_case_moderator_alter_case_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='case',
            name='moderator_note',
        ),
        migrations.RemoveField(
            model_name='case',
            name='reported',
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('action', models.CharField(choices=[('NoAction', 'NoAction'), ('Mute', 'Mute'), ('Ban', 'Ban')], max_length=20)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='moderations.case')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('reported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
