# Generated by Django 4.0.5 on 2022-07-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0004_remove_case_moderator_remove_case_moderator_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement',
            name='case',
        ),
        migrations.AddField(
            model_name='case',
            name='judgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='moderations.judgement'),
        ),
    ]
